name: productbarcode
description: Flutter package for fast search country of product by barcode
version: 1.0.0+4
homepage: "https://github.com/BruSD/product_barcode"
repository: "https://github.com/BruSD/product_barcode"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


